USE [master]
GO
/****** Object:  Database [AirUdC_DB]    Script Date: 14/09/2023 3:12:25 p. m. ******/
CREATE DATABASE [AirUdC_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'AirUdC_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AirUdC_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'AirUdC_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\AirUdC_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [AirUdC_DB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AirUdC_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AirUdC_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AirUdC_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AirUdC_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AirUdC_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AirUdC_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [AirUdC_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AirUdC_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AirUdC_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AirUdC_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AirUdC_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AirUdC_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AirUdC_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AirUdC_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AirUdC_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AirUdC_DB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AirUdC_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AirUdC_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AirUdC_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AirUdC_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AirUdC_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AirUdC_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AirUdC_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AirUdC_DB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [AirUdC_DB] SET  MULTI_USER 
GO
ALTER DATABASE [AirUdC_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AirUdC_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AirUdC_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AirUdC_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [AirUdC_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [AirUdC_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [AirUdC_DB] SET QUERY_STORE = OFF
GO
USE [AirUdC_DB]
GO
/****** Object:  Table [dbo].[City]    Script Date: 14/09/2023 3:12:25 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CityName] [nvarchar](50) NOT NULL,
	[CountryId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Country]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Country](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[FamilyName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[Cellphone] [nvarchar](15) NOT NULL,
	[Photo] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Feedback]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Feedback](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[RateForOwner] [int] NULL,
	[CommentsForOwner] [nvarchar](max) NULL,
	[RateForCustomer] [int] NULL,
	[CommentsForCustomer] [nvarchar](max) NULL,
	[ReservationId] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MultimediaType]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MultimediaType](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[MultimediaTypeName] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Property]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Property](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[PropertyAddress] [nvarchar](200) NOT NULL,
	[CityId] [int] NOT NULL,
	[CustomerAmount] [int] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[Latitude] [nvarchar](20) NOT NULL,
	[Longitude] [nvarchar](20) NOT NULL,
	[OwnerId] [bigint] NOT NULL,
	[CheckinData] [nvarchar](200) NOT NULL,
	[CheckoutData] [nvarchar](200) NOT NULL,
	[Details] [nvarchar](max) NULL,
	[Pets] [bit] NOT NULL,
	[Freezer] [bit] NOT NULL,
	[LaundryService] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyMultimedia]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyMultimedia](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[MultimediaName] [int] NULL,
	[MultimediaLink] [nvarchar](max) NULL,
	[PropertyId] [bigint] NOT NULL,
	[MultimediaTypeId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PropertyOwner]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PropertyOwner](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](100) NOT NULL,
	[FamilyName] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[Cellphone] [nvarchar](15) NOT NULL,
	[Photo] [nvarchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Reservation]    Script Date: 14/09/2023 3:12:26 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Reservation](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[EnterDate] [date] NOT NULL,
	[OutDate] [date] NOT NULL,
	[Price] [decimal](10, 2) NOT NULL,
	[PropertyId] [bigint] NOT NULL,
	[CustomerId] [bigint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[City] ON 
GO
INSERT [dbo].[City] ([Id], [CityName], [CountryId]) VALUES (1, N'Manizales', 1)
GO
INSERT [dbo].[City] ([Id], [CityName], [CountryId]) VALUES (2, N'Sao Paulo city', 2)
GO
SET IDENTITY_INSERT [dbo].[City] OFF
GO
SET IDENTITY_INSERT [dbo].[Country] ON 
GO
INSERT [dbo].[Country] ([Id], [CountryName]) VALUES (1, N'Colombia')
GO
INSERT [dbo].[Country] ([Id], [CountryName]) VALUES (2, N'Brasil')
GO
SET IDENTITY_INSERT [dbo].[Country] OFF
GO
ALTER TABLE [dbo].[Property] ADD  DEFAULT ((1)) FOR [CustomerAmount]
GO
ALTER TABLE [dbo].[Property] ADD  DEFAULT ((0)) FOR [Pets]
GO
ALTER TABLE [dbo].[Property] ADD  DEFAULT ((0)) FOR [Freezer]
GO
ALTER TABLE [dbo].[Property] ADD  DEFAULT ((0)) FOR [LaundryService]
GO
ALTER TABLE [dbo].[City]  WITH CHECK ADD FOREIGN KEY([CountryId])
REFERENCES [dbo].[Country] ([Id])
GO
ALTER TABLE [dbo].[Feedback]  WITH CHECK ADD FOREIGN KEY([ReservationId])
REFERENCES [dbo].[Reservation] ([Id])
GO
ALTER TABLE [dbo].[Property]  WITH CHECK ADD FOREIGN KEY([OwnerId])
REFERENCES [dbo].[PropertyOwner] ([Id])
GO
ALTER TABLE [dbo].[Property]  WITH CHECK ADD  CONSTRAINT [fk_cityId_property] FOREIGN KEY([CityId])
REFERENCES [dbo].[City] ([Id])
GO
ALTER TABLE [dbo].[Property] CHECK CONSTRAINT [fk_cityId_property]
GO
ALTER TABLE [dbo].[PropertyMultimedia]  WITH CHECK ADD FOREIGN KEY([MultimediaTypeId])
REFERENCES [dbo].[MultimediaType] ([Id])
GO
ALTER TABLE [dbo].[PropertyMultimedia]  WITH CHECK ADD FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Property] ([Id])
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [fk_CustomerId_Reservation] FOREIGN KEY([CustomerId])
REFERENCES [dbo].[Customer] ([Id])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [fk_CustomerId_Reservation]
GO
ALTER TABLE [dbo].[Reservation]  WITH CHECK ADD  CONSTRAINT [fk_PropertyId_Reservation] FOREIGN KEY([PropertyId])
REFERENCES [dbo].[Property] ([Id])
GO
ALTER TABLE [dbo].[Reservation] CHECK CONSTRAINT [fk_PropertyId_Reservation]
GO
USE [master]
GO
ALTER DATABASE [AirUdC_DB] SET  READ_WRITE 
GO
