//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirbnbUdc.Repository.Implementation.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public long Id { get; set; }
        public Nullable<int> RateForOwner { get; set; }
        public string CommentsForOwner { get; set; }
        public Nullable<int> RateForCustomer { get; set; }
        public string CommentsForCustomer { get; set; }
        public long ReservationId { get; set; }
    
        public virtual Reservation Reservation { get; set; }
    }
}
